//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class users1
    {
        public int id { get; set; }
        public string name { get; set; }
        public int accountType { get; set; }
        public int balance { get; set; }
    }
}
